name: .NET Core Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        os: [win-x64, win-x86]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c "Debug and Test" -r ${{ matrix.os }}
    - name: Test
      run: dotnet test --verbosity normal -c "Debug and Test"
